### ISSUE TITLE
Cannot use feeder.Yaml literal

### ISSUE THREAD

**Issue by husnaram** [golobby/config#19]
Hi!

Sorry, i got this when used `feeder.Yam{}` on Go v1.15.6 at Linux os.

```
cannot use feeder.Yaml literal (type feeder.Yaml) as type config.Feeder in field value:
    feeder.Yaml does not implement config.Feeder (Feed method has pointer receiver)
```

the result based on example code that i'm try to my self

```go
c, err := config.New(config.Options{
    Feeder: feeder.Yaml{
        Path: "config/env.yaml",
    },
})
if err != nil {
    fmt.Println(err)
}

getConfigName, _ := c.Get("name")
fmt.Println(getConfigName)
```

Can i fix it, if there' mistake on my code? Or something happened in this package?

Thank you.

**Comment by miladrahimi** [comment]
Could you please add your yaml file too?

**Comment by jamesallured** [comment]
So passing `feeder.Yaml{...}` is passing a `feeder.Yaml` literal. `Feeder` is expecting a pointer to a `feeder.Yaml`. You can fix the error by passing the address of the literal, for example:

```go
c, err := config.New(config.Options{
    Feeder: &feeder.Yaml{
        Path: "config/env.yaml",
    },
})
```

I hope this helps you out!

**Comment by husnaram** [comment]
@jamesallured It works.
Thank you very much.
