### ISSUE TITLE
Make env a valid feeder

### ISSUE THREAD

**Issue by amirrezaask** [golobby/config#21]
I think it's better to have a simpler approach to Env variables and treat env as a feeder, not a seperate concept.

**Comment by miladrahimi** [comment]
I'm absolutely agree!
The constructor also should get multiple feeders instead of that config struct!
Env feeders can load data to OS!

**Comment by amirrezaask** [comment]
I will try to make env a feeder as well in a branch I will do a PR when completed

**Comment by amirrezaask** [comment]
@miladrahimi https://github.com/golobby/config/pull/22 it's a WIP but take a look.

**Comment by miladrahimi** [comment]
Looks good man ;)
