### ISSUE TITLE
How we can improve API with generics of go1.18

### ISSUE THREAD

**Issue by amirrezaask** [golobby/config#35]

**Comment by miladrahimi** [comment]
I think we can remove all reflections (something we love :D)
Currently homebrew doesn't have go 18, we should wait and let more platfroms support it before we force users to use it.

**Comment by amirrezaask** [comment]
I actually don't know if we can do it, we use reflection for feeding structs since we need field data I dont know how generics would help there, if we had old Get methods we could use generics to make them type safe and not use interface{}
